// Generated by CoffeeScript 1.6.3
/*
Copyright 2013 Sven Reissmann <sven@0x80.io>

This file is part of ddserver. It is licensed under the terms of the
GNU General Public License version 3. See <http://www.gnu.org/licenses/>.
*/


(function() {
  define(['jquery', 'knockout', 'pager', 'vars', 'bootstrap'], function($, ko, pager, vars) {
    var DashboardModel;
    DashboardModel = (function() {
      function DashboardModel() {}

      return DashboardModel;

    })();
    return DashboardModel;
  });

}).call(this);
