
// Installation manual
== Installation

The following sections describe the installation of ddserver, including
the ddserver-interface, ddserver-updater and the ddserver-recursor.

For testing, a vagrant box is available which will install and start the
ddserver-interface and ddserver-updater in a CentOS virtual machine.
See link:https://github.com/ddserver[https://github.com/ddserver].

=== Prerequisites

ddserver is written in Python and was tested with versions 2.7 and 3.4 of
the python programming language. The installation process is based on python
setuptools. A MySQL database server is needed to allow ddserver to store
user, zone and hostname information. Finally, the PowerDNS server is required
to answer DNS requests.

Also, some packages need to be installed on your system, before you will be
able to compile the needed packages. These include the python and mysql-client
header files, which are available in separate packages on some GNU/Linux distributions.

If you are using Debian GNU/Linux or Ubuntu, please install the following packages.
For other distributions, find the corresponding packages to install.

[source, bash]
----
libmysqlclient-dev 
python-dev
python-setuptools
----

=== Getting the Source

ddserver is available from link:https://github.com/ddserver/ddserver[GitHub].
Releases can be downloaded from there, but using git to clone the current
state of the project is the preferred way. The master branch will always
point to the latest stable version of ddserver.

To get the source please use git to clone the ddserver repository.

[source, bash]
----
cd /tmp
git clone https://github.com/ddserver/ddserver.git
----

=== Creating a virtual environment

The preferred way of installing ddserver is by using a python virtual
environment. This keeps your system clean and avoids conflicting packages.
To start, first create a directory of your choice (in the example, I'm using
/opt/ddserver), and then create a virtual environment in that directory.

[source, bash]
----
mkdir /opt/ddserver
cd /opt/ddserver
virtualenv .
----

The virtual environment is now created and can be activated by issuing the
following commands.

[source, bash]
----
cd /opt/ddserver
source ./bin/activate
----

You can recognize that you are inside of your virtual environment by your
PROMPT being prefixed with (ddserver).

=== Installing ddserver

Change to the directory where you cloned ddserver to and use
'python-setuptools' to install ddserver

[source, bash]
----
cd /tmp/ddserver
python setup.py install
----

After this steps is completed, ddserver has been installed. All ddserver
related files have been installed to the virtual environment. There are
some important locations inside your virtual environment.

[cols="2*"]
|===
|/opt/ddserver/bin
|the ddserver executables

|/opt/ddserver/lib/python*/site-packages/ddserver-*.egg/ddserver
|the ddserver python packages

|/opt/ddserver/lib/python*/site-packages/ddserver-*.egg/doc
|the ddserver documentation, example configuration and database layout

|===

=== Installing the database

ddserver uses a MySQL database backend to store information about user
accounts, zones, hostnames, etc. To install the ddserver database schema,
first create a database and a database user for ddserver.

[source, mysql]
----
mysql -u root -p

mysql> CREATE DATABASE ddserver;
mysql> CREATE USER 'ddserver'@'localhost' IDENTIFIED BY 'YourSecurePassword';
mysql> GRANT USAGE ON *.* TO 'ddserver'@'localhost' IDENTIFIED BY 'YourSecurePassword' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
mysql> GRANT SELECT, INSERT, UPDATE, DELETE ON `ddserver`.* TO 'ddserver'@'localhost';
----

After the database was created, you can install the ddserver database
schema by usng the following command.

[source, bash]
----
mysql -u root -p ddserver < /opt/ddserver/lib/python*/site-packages/ddserver-*.egg/doc/db/schema.sql
----

=== Installing the configuration file

By default, ddserver will try to load its configuration file from
/etc/ddserver/ddserver.conf. You should now copy the example configuration
file to this location.

[source, bash]
----
mkdir /etc/ddserver
cp /opt/ddserver/lib/python*/site-packages/ddserver-*.egg/doc/conf/ddserver.conf.example /etc/ddserver/ddserver.conf
cp /opt/ddserver/lib/python*/site-packages/ddserver-*.egg/doc/conf/motd /etc/ddserver/
----

Congratz, you installed ddserver!

TIP: When installing the default database schema, an initial user will be installed to login to the WebUI.

The default login is
[source, bash]
----
username: admin
password: admin
----

//EOF