
// User manual
== User manual

The following sections give a brief overview of the usage of the ddserver WebUI.
Default account

While installing the ddserver database schema, an administrator user is created with the following credentials:

- Username: admin
- Password: admin

=== User registration

Depending on your configuration, account creation may be enabled or disabled.
If it is enabled, new user accounts can be created/requested using the signup form.

If account creation is enabled in your configuration file, you can specify a comma-separated list of email-domains (or use the keyword any) to allow users to complete the account registration without the need to be accepted by an administrator.
The default setting of this configuration parameter is to allow any user to complete the registration process by email-activation.

If a user registers using an email address that is not specified in the list of allowed_maildomains, an administrator has to accept the new user, before an activation email is sent, allowing the user to finish registration.

=== Adding a dynamic zone (suffix)

Each zone you want to make available by your ddserver installation, needs to be handled by the PowerDNS server, your ddserver-recursor is connected to.
That means, you have to configure zone-delegation of the desired zone to your PowerDNS server(s).

If you want to use example.com as your dynamic zone

- Configure your PowerDNS server(s) to be authoritative
- Add example.com to the available suffixes in the ddserver WebUI

TIP: Each zone available in ddserver, users are allowed to add any hostname (subdomain) to (including stuff like www or mail). You can prevent hostnames to be added by just pre-adding them in your admin account.

WARNING: You can not have duplicate zone records, i.e. by specifying a subdomain in the PowerDNS gmysql backend and ddserver at the same time.

=== Adding a hostname

After at least one dynamic zone is available, users can start adding hostnames.
The number of hostnames each user can add depends on your configuration (default = 5).

A hostname can consist of a maximum of 63 alphanumeric characters.
The special characters - (minus) and . (period) are allowed, however they can not be the first character of a hostname.

Each hostname is assigned a password, that is used to update the IP address of the hostname.
If you want to update multiple hostnames at once (which is a specified usecase of the no-ip protocol), you have to assign the same password to these hostnames.

//EOF